spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minipay?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: topy
    password: 1234
    name: minipay

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

sonar:
  organization: dojindo
  projectKey: dojindo_minipay-jinyoung
  sources: .

fcm:
  project-id: minipay-remainder
  service-account-key-path: firebase/key/minipay-remainder-key.json

